services:
  - type: web
    name: predictify-ai
    env: python
    buildCommand: |
      pip install setuptools wheel
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free